#! /usr/bin/perl -w
#
# creates tv_cards.ycp - a database with the TV cards
#
# $1 - the CARDLIST.bttv source file
# $2 - the CARDLIST.saa7134 source file
# $3 - the CARDLIST.cx88 source file
# $4 - the CARDLIST.ivtv source file
# $5 - the CARDLIST.em28xx source file
# $6 - the CARDLIST.cx23885 source file
# ...more to come...

if ($#ARGV < 1)
{
    die "Please, specify the source files as parameters!";
}

# Parameters
$bttv_cardlist_fname = $ARGV[0];
$saa7134_cardlist_fname = $ARGV[1];
$cx88_cardlist_fname = $ARGV[2];
$ivtv_cardlist_fname = $ARGV[3];
$em28xx_cardlist_fname = $ARGV[4];
$cx23885_cardlist_fname = $ARGV[5];
# ... more to come ...

# Names to translate
%clean_names =
    (
    	"*** UNKNOWN/GENERIC ***" => " // Item text in the list of cards\n\t\t\t_(\"Unknown bttv Card\")",
    	"Askey CPH05X/06X (bt878) [many vendors]" => "\"CPH05X/06X (bt878)\"",
    	"Flyvideo 98EZ (capture only)" => " // Item text in the cards list (translate \"capture only\")\n\t\t\t\t\t_(\"FlyVideo 98EZ (capture only)\")",
    );

# List of the known vendors
$known_vendors = 
    "\(ATI\|Askey\|Asus\|AVerMedia\|AverTV\|Beholder\|BESTBUY\|Compro\|DViCO\|FlyVideo\|GrandTec\|Hauppauge\|Intel\|".
    "KWorld\|Leadtek\|LifeView\|MATRIX-Vision\|MIRO\|MSI\|Osprey\|Phoebe\|Pinnacle\|Prolink\|".
    "STB\|Terratec\|Zoltrix\)";

# This is for the sort function...
sub get_name_cmp
{
    $ref = shift;
    $name = $ref->{"name"};
    
    if ($name =~ /^_\(/)
    {
	$name = "!".$name; # To change the order...
    }
    $name =~ tr/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/;

    return $name;
}

# Print the database in its List-of-hashes form
sub dbPrint
{
    $vendor_name = shift;
    $to_print_ref = shift;
    @to_print = @{$to_print_ref};
    
    print "    \$[ \"name\" : $vendor_name,\n";
    print "       \"cards\" :\n";
    print "\t[\n";

    $first = 1;
    foreach $ref (@to_print)
    {
	# we do not add a "," before the first entry
	if ($first)
	{
	    $first = 0;
	}
	else
	{
	    print ",\n";
	}
	print "\t    \$[ \"name\" : $ref->{\"name\"},\n";
	print "\t       \"module\" : [ $ref->{\"module\"} ],\n";
	print "\t       \"parameters\" : \$[ $ref->{\"module\"} : $ref->{\"parameters\"}\n ]";
	print "\t    ]";
    }

    print "\n\t]\n";
    print "    ]";
}

# Read database
sub ReadDatabase
{
    $name = shift;
    $driver = shift;
    open (DB, $name) or die "Cannot open $name!";

    @card_array = ();

    while ($_ = <DB>)
    {
	# create the line
	if (/^\s*(\S*)\s*->\s*(\S*.*\S)\s*$/)
	{
	    # Clean the name
	    my $card_name = $2;

	    if (defined $clean_names{$card_name})
	    {
		$card_name = $clean_names{$card_name};
	    }
	    else
	    {
		if ($card_name =~ /^(.*\S)\s*\[.*:.*\]/)
		{
		    $card_name = $1;
		}
		$card_name = "\"$card_name\"";
	    }

	    if ($card_name eq "\"UNKNOWN/GENERIC\"")
	    {
		$card_name = " // Item text in the list of cards\n\t\t\t_(\"Unknown $driver Card\")";
	    }

	    $item =
		{ "name" => $card_name,
		  "module" => "\"$driver\"",
		  "parameters" => "\$[ \"card\" : \"$1\" ]"
		};
	    
	    push @card_array, $item;
	}
    }
    
    close(DB);

    return @card_array;
}


# And do it!

print "/* YaST2 TV cards database\n";
print " *\n";
print " * Generated ".qx(date);
print " * From: @ARGV\n";
print " */";
print "\n";
print "{\n";
print "textdomain \"tv\";\n";
print "return [\n";

@cards = ();

# Collect the parameters
push @cards, ReadDatabase($bttv_cardlist_fname, "bttv");
push @cards, ReadDatabase($saa7134_cardlist_fname, "saa7134");
push @cards, ReadDatabase($cx88_cardlist_fname, "cx88xx");
push @cards, ReadDatabase($ivtv_cardlist_fname, "ivtv");
push @cards, ReadDatabase($em28xx_cardlist_fname, "em28xx");
push @cards, ReadDatabase($cx23885_cardlist_fname, "cx23885");
#...more to come...

# Sort @cards
@cards = sort { get_name_cmp($a) cmp get_name_cmp($b) } @cards;

# Sort it according to known vendors
$vendors = ();
$index = 0;

my $regexp = $known_vendors;

if ($known_vendors =~ /\((.*)\)/)
{
    $regexp = $1;
}
  
@vendor_list = split(/\|/, $regexp);

while ($index <= $#cards)
{
    if ($cards[$index]->{"name"} =~ /^"($known_vendors)/i)
    {
	$vendor = $1;
	    
	foreach my $v (@vendor_list)
	{
	    if ($vendor =~ /($v)/i)
	    {
		$vendor = $v;
	    }
	}

	# Remove the found card
	$ref = splice(@cards, $index, 1);

	# Give it to $vendors
	if (defined $vendors{$vendor})
	{
	    push @{$vendors{$vendor}}, ( $ref );
	}
	else
	{
	    $vendors{$vendor} = [ $ref ];
	}
    }
    else
    {
	$index++;
    }
}

# Print it now
dbPrint(" // Item text in the list of card vendors\n\t\t\t\t_(\"Other vendors\")", \@cards);
foreach $vendor (sort keys %vendors)
{
    print ",\n";
    dbPrint("\"$vendor\"", $vendors{$vendor});
}
    
print "\n];\n}\n";

# The end...
